# docker-compose.yml

devd8:
  build: .
  dockerfile: Dockerfile
  environment:
    VIRTUAL_HOST: dev.d8.com
    PHP_OPCACHE: enabled
  volumes:
    - ".:/var/www"
  links:
    - wmysql
  ports:
    - "80"
    - "443"
    - "22"

d8mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: drupal
    VIRTUAL_PORT: 3306
  ports:
    - "3306"
